#!/bin/sh
set -o errexit

if [ ! -f "/blockade/blockade.yaml" -a ! -f "/blockade/blockade.yml" ]; then
    echo "Could not find blockade.yaml mounted in /blockade"
    exit 1
fi
cd /blockade
nsenter --target 1 --net blockade "$@"
